### ISSUE TITLE
[FEATURE]: Addition of ORM based code for tables 

### ISSUE THREAD

**Issue by AbhijithGanesh** [dokc/rap-god-api#15]
### Would you like to have a new feature? Please describe.

As per the schema mentioned in the [Readme](https://github.com/dokc/how-to-dok#database-schema)  it'd be very nice if the contributors refer to the Cassandra-Express [docs](https://express-cassandra.readthedocs.io/en/latest/) and write `javascript` queries using the library:

Sub-tasks: 
- [ ] Singers Table
- [ ] Rap Lyrics

- [ ] Lyrics Table

### How would this feature be beneficial for the project

This would establish migrations for the project.

**Comment by AbhijithGanesh** [comment]
[Reference](https://github.com/dokc/how-to-dok/blob/main/resources/database/ERD.png)

**Comment by chetak123** [comment]
Can I take up this issue please ?, I am very new to this and I have previously used json structure to write simple queries in mongoDb but never used cassandra before.

**Comment by AbhijithGanesh** [comment]
We d like to do this task wise and provide opportunities to all Devs, let us convert it into subtasks, we'll definitely assign one to you @chetak123

**Comment by shreemaan-abhishek** [comment]
Closed in favor of [this](https://github.com/dokc/rap-god-api/issues/27#issuecomment-1086125098) comment.
