### ISSUE TITLE
Write schema for the database using the express app defined.

### ISSUE THREAD

**Issue by AmitKarnam** [dokc/rap-god-api#27]
### What would you like to share?

The schema has been updated from 3 tables to 1 table.  Now with the schema definition up to date, one can go ahead and write the updated schema onto code.

Link to Schema :  [Rap-God-API](https://user-images.githubusercontent.com/56480746/161067102-f969e051-081d-49a0-968e-486be915a062.png)

**Comment by chetak123** [comment]
> This potentially looks like a duplicate of #15

Yeah absolutely. 
Actually I have previously written schema for mongodb and being total beginner and curious about cs-db I am interested in this issue. Also I wanted to know what would be the keyspace and primary key structure for table (considering first we write for cassandra db)

**Comment by AmitKarnam** [comment]
Keyspace can be kept to be Simple Strategy' for now and the primary key can be a combination of Singer_name and Lyricist_Name.

Would that be oknto start work with? 

Cc :  @shreemaan-abhishek @AbhijithGanesh @yashgangwar7558

**Comment by chetak123** [comment]
Hey @AmitKarnam I have created an initial draft for schema, please have a look.

**Comment by shreemaan-abhishek** [comment]
@AmitKarnam what's your response on [this](https://github.com/dokc/rap-god-api/issues/27#issuecomment-1084735648), asking because we can't have multiple issues addressing the same task.

**Comment by AmitKarnam** [comment]
We can keep this Issue nd close #15 .

**Comment by yashgangwar7558** [comment]
> Keyspace can be kept to be Simple Strategy for now and the primary key can be a combination of Singer_name and Lyricist_Name.
> 
> Would that be ok to start work with?
> 
> Cc : @shreemaan-abhishek @AbhijithGanesh @yashgangwar7558

Since we have only one singer i.e Bart and if we make singer name as Partition key.....than one partition(for Bart) will be much bigger than the other one(for other singers). But we have to avoid hot partitions i.e all partitions should be almost equal

**Comment by AmitKarnam** [comment]
> > Keyspace can be kept to be Simple Strategy for now and the primary key can be a combination of Singer_name and Lyricist_Name.
> > 
> > Would that be ok to start work with?
> > 
> > Cc : @shreemaan-abhishek @AbhijithGanesh @yashgangwar7558
> 
> Since we have only one singer i.e Bart and if we make singer name as Partition key.....than one partition(for Bart) will be much bigger than the other one(for other singers). But we have to avoid hot partitions i.e all partitions should be almost equal


Can thus solved by creating a Rap id for each Rap? Tats something @chetak123 suggested after he built the initial schema.

Check out the #28 conversation.

**Comment by chetak123** [comment]
Hey @AmitKarnam I have made pr for schema please have a look 
(Also played with insertion of data in separate branch , but I think making proper api endpoints for insertion and deletion would be more beneficial 😅)
